let x=245
let y=92.45
console.log(x.toString())
console.log(y.toExponential())
console.log(y.toExponential(2))
console.log(y.toExponential(5))
console.log(x.toExponential(5))
console.log(y.toFixed())
console.log(y.toFixed(1))
console.log(y.toFixed(5))
console.log(y.toPrecision(5))
console.log(y.valueOf(1))
console.log(Number(true))
console.log(typeof(Number("67")))
console.log(parseFloat("values"))